FROM python:3.12-slim

WORKDIR /app

# Копируем pyproject и lock
COPY pyproject.toml uv.lock ./

# Устанавливаем uv
RUN python -m pip install --no-cache-dir uv

# Устанавливаем зависимости для разработки
RUN uv sync

# Копируем весь код
COPY ./app /app/app

# Dev-сервер с hot reload
CMD ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8001"]
